allowBuilds:
  esbuild: true
  sharp: true
trustLockfile: true
minimumReleaseAgeExclude:
  - decap-cms-app@3.15.0
  - decap-cms-backend-aws-cognito-github-proxy@3.7.0
  - decap-cms-backend-forgejo@3.4.0
  - decap-cms-backend-github@3.8.0
  - decap-cms-backend-proxy@3.5.0
  - decap-cms-backend-test@3.4.0
  - decap-cms-core@3.17.0
  - decap-cms-editor-component-image@3.4.0
  - decap-cms-lib-util@3.8.0
  - decap-cms-locales@3.8.0
  - decap-cms-ui-default@3.9.0
  - decap-cms-widget-code@3.7.0
  - decap-cms-widget-colorstring@3.3.0
  - decap-cms-widget-datetime@3.6.0
  - decap-cms-widget-file@3.5.0
  - decap-cms-widget-image@3.4.0
  - decap-cms-widget-map@3.3.0
  - decap-cms-widget-markdown@3.11.0
  - decap-cms-widget-number@3.4.0
  - decap-cms-widget-object@3.7.0
  - decap-cms-widget-relation@3.7.0
  - decap-cms-widget-richtext@3.5.0
  - decap-cms-widget-select@3.4.0
  - decap-cms-widget-string@3.3.0
  - decap-cms-widget-text@3.3.0
  - decap-cms-widget-uuid@3.1.0
